name: Auto-Generate Manifest
on:
  push:
    branches: [ main ]
    paths:
      - 'playbooks/**/info.json'
  workflow_dispatch: # Permet de lancer le bouton manuellement si besoin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Passage en v4 pour Node 24

      - name: Generate Manifest
        run: |
          # On cherche tous les info.json, on les fusionne proprement avec jq
          # Le flag -s (slurp) crée automatiquement le tableau avec les virgules
          find playbooks -name "info.json" | xargs cat | jq -s '{version: "1.0.0", packages: .}' > manifest.json
          
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add manifest.json
          # On commit si changement, sinon on sort proprement
          git commit -m "chore: auto-update manifest.json [skip ci]" || exit 0
          # On force le push pour écraser les conflits de l'automate
          git push --force origin main
